package com.yoggo.dleandroidclient.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORIES.
 */
public class Categories {

    private Long id;
    private String Name;
    private String AltName;
    private String ParentId;

    public Categories() {
    }

    public Categories(Long id) {
        this.id = id;
    }

    public Categories(Long id, String Name, String AltName, String ParentId) {
        this.id = id;
        this.Name = Name;
        this.AltName = AltName;
        this.ParentId = ParentId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getAltName() {
        return AltName;
    }

    public void setAltName(String AltName) {
        this.AltName = AltName;
    }

    public String getParentId() {
        return ParentId;
    }

    public void setParentId(String ParentId) {
        this.ParentId = ParentId;
    }

}
