package com.yoggo.dleandroidclient.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMMENTARIES.
 */
public class Commentaries {

    private Long id;
    private Long NewsId;
    private String Content;
    private String Author;
    private String Date;
    private String UserId;

    public Commentaries() {
    }

    public Commentaries(Long id) {
        this.id = id;
    }

    public Commentaries(Long id, Long NewsId, String Content, String Author, String Date, String UserId) {
        this.id = id;
        this.NewsId = NewsId;
        this.Content = Content;
        this.Author = Author;
        this.Date = Date;
        this.UserId = UserId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getNewsId() {
        return NewsId;
    }

    public void setNewsId(Long NewsId) {
        this.NewsId = NewsId;
    }

    public String getContent() {
        return Content;
    }

    public void setContent(String Content) {
        this.Content = Content;
    }

    public String getAuthor() {
        return Author;
    }

    public void setAuthor(String Author) {
        this.Author = Author;
    }

    public String getDate() {
        return Date;
    }

    public void setDate(String Date) {
        this.Date = Date;
    }

    public String getUserId() {
        return UserId;
    }

    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

}
