package com.yoggo.dleandroidclient.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS.
 */
public class News {

    private Long id;
    private String Title;
    private String ShortStory;
    private String FullStory;
    private String Date;
    private String Author;
    private String NewsRead;
    private String Rating;
    private String CommNum;
    private String UserId;
    private String Category;
    private byte[] Image;

    public News() {
    }

    public News(Long id) {
        this.id = id;
    }

    public News(Long id, String Title, String ShortStory, String FullStory, String Date, String Author, String NewsRead, String Rating, String CommNum, String UserId, String Category, byte[] Image) {
        this.id = id;
        this.Title = Title;
        this.ShortStory = ShortStory;
        this.FullStory = FullStory;
        this.Date = Date;
        this.Author = Author;
        this.NewsRead = NewsRead;
        this.Rating = Rating;
        this.CommNum = CommNum;
        this.UserId = UserId;
        this.Category = Category;
        this.Image = Image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getShortStory() {
        return ShortStory;
    }

    public void setShortStory(String ShortStory) {
        this.ShortStory = ShortStory;
    }

    public String getFullStory() {
        return FullStory;
    }

    public void setFullStory(String FullStory) {
        this.FullStory = FullStory;
    }

    public String getDate() {
        return Date;
    }

    public void setDate(String Date) {
        this.Date = Date;
    }

    public String getAuthor() {
        return Author;
    }

    public void setAuthor(String Author) {
        this.Author = Author;
    }

    public String getNewsRead() {
        return NewsRead;
    }

    public void setNewsRead(String NewsRead) {
        this.NewsRead = NewsRead;
    }

    public String getRating() {
        return Rating;
    }

    public void setRating(String Rating) {
        this.Rating = Rating;
    }

    public String getCommNum() {
        return CommNum;
    }

    public void setCommNum(String CommNum) {
        this.CommNum = CommNum;
    }

    public String getUserId() {
        return UserId;
    }

    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    public String getCategory() {
        return Category;
    }

    public void setCategory(String Category) {
        this.Category = Category;
    }

    public byte[] getImage() {
        return Image;
    }

    public void setImage(byte[] Image) {
        this.Image = Image;
    }

}
